### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by dmitrif** [alexkuz/redux-pagan#2]
Hi!

Currently on version `"redux-pagan": "^0.1.3",`. A peer is having a problem with receiving the following runtime error:

```
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function._module3.default._resolveFilename (/Users/mhogg/Github/frontend-service/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mhogg/Github/frontend-service/node_modules/redux-pagan/lib/index.js:3:30)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mhogg/Github/frontend-service/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:344:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by alexkuz** [comment]
Yeah, it depends on `babel-runtime` - I'm not sure, is it better to add it to dependencies or just try to get rid of it. For now, just install a package.

**Comment by dmitrif** [comment]
Thanks man. Installed the runtime that made the issue go ahead away. Out of
curiosity what is the runtime being used for?

On Thursday, 11 February 2016, Alexander Kuznetsov notifications@github.com
wrote:

> Yeah, it depends on babel-runtime - I'm not sure, is it better to add it
> to dependencies or just try to get rid of it. For now, just install a
> package.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexkuz/redux-pagan/issues/2#issuecomment-182798173.

## 

---

Dmitri Farkov
647.898.5054

**Comment by alexkuz** [comment]
Babel needs some helper functions for ES6 features and polyfills, so to avoid code repetition in your project it imports them from an external package.

**Comment by dmitrif** [comment]
Thanks :)
